name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Check out repository
      - uses: actions/checkout@v2

      # Set up Node.js
      - uses: actions/setup-node@v2
        with: 
          node-version: 20

      # Set up MySQL database
      - uses: mirromutth/mysql-action@v8.3.13
        with:
          mysql-database: laravel-test-db
          mysql-user: laravel_test_user
          mysql-password: example

      # Cache dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      # Set up environment
      - name: Copy .env
        run: cp .env.example .env

      # Install dependencies
      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install Node dependencies
        run: npm ci

      # Set up project
      - name: Setup Project
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
          npm run build
      - name: Directory Permissions
        run: chmod 755 -R storage bootstrap/cache

      # Run Unit Tests
      - name: Run Unit Tests
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
        run: php artisan test

      # Deploy to Server
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd apps
            cd /home/abdulkco/public_html/laravel/laravel-blog-app
            git pull
            npm ci
            npm run prod
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
